# Generated by Django 3.1.12 on 2025-04-16 13:17

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ll_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('cost', models.FloatField()),
                ('product_image', models.CharField(max_length=500)),
                ('length', models.CharField(blank=True, max_length=50)),
                ('width', models.CharField(blank=True, max_length=50)),
                ('height', models.CharField(blank=True, max_length=50)),
                ('weight', models.CharField(blank=True, max_length=50)),
                ('features', djongo.models.fields.JSONField()),
                ('state', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('details', models.TextField()),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ll_app.businesssignup')),
            ],
        ),
    ]
