# Generated by Django 3.1.12 on 2025-04-16 13:44

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ll_app', '0002_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='business',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_image',
        ),
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='features',
            field=djongo.models.fields.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='product',
            name='height',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='length',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='width',
            field=models.CharField(max_length=100),
        ),
    ]
