# Generated by Django 3.1.12 on 2025-05-05 04:15

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ll_app', '0005_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cost',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='features',
            field=djongo.models.fields.JSONField(),
        ),
    ]
